language: cpp
sudo: required
compiler:
- gcc
os:
- linux
dist: xenial
script: make all

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "QNUA+Sc8SkUTfP3iareQkr1iaLb192xjn6pUBZyVs0M4BdO5/VkCzuL9w9lcI64893vx0gT+Rn3yzwI+VHCz7WJxVqTs7WpVb1BIuIxLKu3HwvXwRfpG4n5wic2iyxXtvzVM8q3UMrcMoV5+s22iWKVUQ3RPEFqX4QyD7EP+BzncJJBrttlw1Vm61HwYEKuSrtQlUUXnvmaq40CSoh5wXOnejCTWK9ANtIWxfa6nOPbU5Ty9ZgBEGqcRDL/tZVPS6SbKMGRpmh3PoQ8oOpteuSOb/59QWhGQ2umjlm3E1aRXX4WPgvUym0cV6EU4HFuKQlg7fKPnG6g1mJ25K2BFeGsFwDaxlpTBYpe5kxubFmQ37neSR/5JRreGa9SJbwzzcFqNWiLy3r/ny+yJ28N8OxeEwoIB8hvxG/lNW7YmL4GH4y4NQzLlBuVxKkINGTyk+L9/R4sBpdiNZw+agEs3mjb1St6AKLYM6T0jMCGjF4kXq+LzXZPF4ru3PeHy0wtwYWCYr2Qbzl3mIOxouB5XejzeGszL8igk+5aBjG30Kplu0oEdMdOWIBI32i+NrmIMm9dZwefVvWlLXBC6L3EiiHhgY+K23LALX2mOf5eFKS7M41KQeknZYbWLjWTL8iYgKtbcvrYs79k/a1uCTUqrD7sBsD2MSmi6HZc9IprgJF8="

before_install:
  - sudo apt-get install -y build-essential libsdl2-dev libboost-program-options-dev
  - echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-

addons:
  coverity_scan:
    project:
      name: "MoleskiCoder/cpp_chip8"
      description: "Build submitted via Travis CI"
    notification_email: adrian.conlon@gmail.com
    build_command_prepend: "make clean"
    build_command:   "make"
    branch_pattern: coverity_scan
